[tool.poetry]
name = "templatized-alu"
version = "0.0.0"
description = "Templatized ALU"
authors = [
    "Juwon Jun <jami3jun@uw.edu>",
    "Ayush Kulkarni <ayushk22@uw.edu>"
]
readme = "README.md"
packages = [
    {include = "alugen"},
]

[tool.poetry.dependencies]
python = ">=3.12"
future = "*"
jinja2 = "*"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.group.dev]
optional = true


[tool.poetry.group.dev.dependencies]
sphinx = "*"
furo = "*"
mypy = "*"
black = "*"
pytest = "*"
pytest-cov = "*"
